site_name: vrbi
site_description: A VR based neural interface
site_author: einhep

repo_url: https://github.com/einhep/vrbi
edit_uri: https://github.com/einhep/vrbi/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributor Guide: about/contributing.md
    - License: about/license.md
